name: 'Run Attestation Agent and Attestation Service'
runs:
  using: "composite"
  steps:
    - name: Prepare attestation-agent
      shell: bash
      run: |
        set -e
        set -x

        yum install -y attestation-agent
        RUST_LOG=debug attestation-agent --attestation_sock unix:///run/confidential-containers/attestation-agent/attestation-agent.sock &

    - name: Prepare attestation-service
      shell: bash
      run: |
        set -e
        set -x

        yum install -y trustee

        # Prepare certificates
        yum install -y jq openssl
        openssl ecparam -genkey -name prime256v1 -out /tmp/as-ca.key
        openssl req -x509 -sha256 -nodes -days 365 -key /tmp/as-ca.key -out /tmp/as-ca.pem -subj "/O=Trustee CA" \
            -addext keyUsage=critical,cRLSign,keyCertSign,digitalSignature
        openssl ecparam -genkey -name prime256v1 -out /tmp/as.key
        openssl req -new -key /tmp/as.key -out /tmp/as.csr -subj "/CN=Trustee/O=Trustee CA"
        openssl x509 -req -in /tmp/as.csr -CA /tmp/as-ca.pem -CAkey /tmp/as-ca.key -CAcreateserial -out /tmp/as.pem -days 365 -extensions v3_req -extfile <(echo -e "[v3_req]\nsubjectKeyIdentifier = hash") -sha256

        # Create full certificate chain file
        cat /tmp/as.pem /tmp/as-ca.pem > /tmp/as-full.pem

        # Generate attestation-service config
        cat /etc/trustee/as-config.json | jq '.attestation_token_broker.signer.cert_path="/tmp/as-full.pem" | .attestation_token_broker.signer.key_path="/tmp/as.key" | .rvps_config={"type":"BuiltIn","storage":{"type":"LocalFs"}}' > /tmp/config_with_cert.json
        RUST_LOG=debug restful-as --socket 0.0.0.0:8080 --config-file /tmp/config_with_cert.json &
