use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::prelude::BASE64_STANDARD;
use base64::Engine as _;
use flatten_json_object::Flattener;
use kbs_types::Tee;
use serde::{Deserialize, Serialize};
use serde_bytes::ByteBuf;
use serde_json::{json, Value};

use crate::cert::dice::cbor::{
    HashAlgoIanaId, OCBR_TAG_EVIDENCE_COCO_EVIDENCE, OCBR_TAG_EVIDENCE_COCO_TOKEN,
};
use crate::crypto::HashAlgo;
use crate::errors::*;
use crate::tee::claims::Claims;
use crate::tee::{DiceParseEvidenceOutput, GenericEvidence, ReportData};

/// Hash algorithm types used by attestation-service
#[derive(Serialize, Deserialize)]
pub enum AttestationServiceHashAlgo {
    #[serde(rename = "sha256")]
    Sha256,
    #[serde(rename = "sha384")]
    Sha384,
    #[serde(rename = "sha512")]
    Sha512,
}

impl AttestationServiceHashAlgo {
    pub fn str_id(&self) -> &'static str {
        match self {
            Self::Sha256 => "sha256",
            Self::Sha384 => "sha384",
            Self::Sha512 => "sha512",
        }
    }
}

impl From<HashAlgo> for AttestationServiceHashAlgo {
    fn from(hash_algo: HashAlgo) -> Self {
        match hash_algo {
            HashAlgo::Sha256 => Self::Sha256,
            HashAlgo::Sha384 => Self::Sha384,
            HashAlgo::Sha512 => Self::Sha512,
        }
    }
}

impl From<AttestationServiceHashAlgo> for HashAlgo {
    fn from(as_hash_algo: AttestationServiceHashAlgo) -> Self {
        match as_hash_algo {
            AttestationServiceHashAlgo::Sha256 => Self::Sha256,
            AttestationServiceHashAlgo::Sha384 => Self::Sha384,
            AttestationServiceHashAlgo::Sha512 => Self::Sha512,
        }
    }
}

/// Convert Tee to its string representation for API calls.
pub fn tee_to_string(tee: Tee) -> Result<String> {
    serde_json::to_value(tee)
        .ok()
        .and_then(|v| v.as_str().map(|s| s.to_string()))
        .ok_or_else(|| Error::TeeTypeToStringFailed(tee))
}

/// Convert Tee to its string representation for API calls.
pub fn tee_from_str(tee_type: &str) -> Result<Tee> {
    serde_json::from_value::<Tee>(serde_json::Value::String(tee_type.to_string())).map_err(|_| {
        Error::TeeTypeFromStringFailed {
            tee_type: tee_type.to_string(),
        }
    })
}

#[derive(Clone)]
pub struct CocoEvidence {
    pub(self) aa_tee_type: Tee,
    /// Raw evidence generated by attestation-agent
    pub(self) aa_evidence: Vec<u8>,
    /// Additional evidence generated by attestation-agent (e.g. device tee evidence)
    pub(self) aa_additional_evidence: Option<Vec<u8>>,
    /// The structed runtime data json which is passed to attestation-agent for generating the evidence, should be hashed with aa_runtime_data_algo.
    pub(self) aa_runtime_data: String,
    /// The hash algorithm used for calculating hash of aa_runtime_data.
    pub(self) aa_runtime_data_hash_algo: HashAlgo,
}

impl CocoEvidence {
    #[allow(unused)]
    pub(crate) fn new(
        aa_tee_type: Tee,
        aa_evidence: Vec<u8>,
        aa_additional_evidence: Option<Vec<u8>>,
        aa_runtime_data: String,
        aa_runtime_data_hash_algo: HashAlgo,
    ) -> Result<Self> {
        Ok(Self {
            aa_tee_type,
            aa_evidence,
            aa_additional_evidence,
            aa_runtime_data,
            aa_runtime_data_hash_algo,
        })
    }

    pub(crate) fn get_tee_type(&self) -> &Tee {
        &self.aa_tee_type
    }

    pub(crate) fn aa_evidence_ref(&self) -> &[u8] {
        &self.aa_evidence
    }

    pub(crate) fn aa_additional_evidence_ref(&self) -> &Option<Vec<u8>> {
        &self.aa_additional_evidence
    }

    pub(crate) fn aa_runtime_data_ref(&self) -> &str {
        &self.aa_runtime_data
    }

    pub(crate) fn get_aa_runtime_data_hash_algo(&self) -> HashAlgo {
        self.aa_runtime_data_hash_algo
    }

    pub(crate) fn wrap_runtime_data_as_structed(
        report_data: &ReportData,
    ) -> Result<serde_json::Value> {
        match report_data {
            ReportData::Raw(report_data) => {
                Ok(json!({"rats-rs.raw_runtime_data": URL_SAFE_NO_PAD.encode(report_data)}))
            }
            ReportData::Claims(claims) => {
                serde_json::to_value(claims).map_err(Error::SerializeClaimsToJsonFailed)
            }
        }
    }

    pub fn serialize_to_json(&self) -> serde_json::Result<serde_json::Value> {
        serde_json::to_value(self.into_json_helper())
    }

    pub fn deserialize_from_json(value: serde_json::Value) -> Result<Self> {
        Self::from_json_helper(
            serde_json::from_value::<CocoEvidenceJsonHelper>(value)
                .map_err(Error::DeserializeEvidenceFromJsonFailed)?,
        )
    }
}

impl GenericEvidence for CocoEvidence {
    fn get_dice_cbor_tag(&self) -> u64 {
        OCBR_TAG_EVIDENCE_COCO_EVIDENCE
    }

    fn get_dice_raw_evidence(&self) -> Result<Vec<u8>> {
        let mut res = vec![];
        ciborium::into_writer(&self.into_cbor_helper(), &mut res)
            .map_err(Error::CborSerializationFailed)?;
        Ok(res)
    }

    fn get_claims(&self) -> Result<Claims> {
        // Return empty claims here since the structure of AA evidence is opaque.
        Ok(Claims::default())
    }

    fn create_evidence_from_dice(
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> DiceParseEvidenceOutput<Self> {
        if cbor_tag == OCBR_TAG_EVIDENCE_COCO_EVIDENCE {
            match ciborium::from_reader::<CocoEvidenceCborHelper, _>(raw_evidence)
                .map_err(Error::CborDeserializationFailed)
                .and_then(CocoEvidence::from_cbor_helper)
            {
                Ok(v) => DiceParseEvidenceOutput::Ok(v),
                Err(e) => DiceParseEvidenceOutput::MatchButInvalid(e),
            }
        } else {
            DiceParseEvidenceOutput::NotMatch
        }
    }
}

pub struct CocoAsToken {
    data: String,
}

impl CocoAsToken {
    /// Create a new CocoAsToken instance from a attestation result JWT.
    pub fn new(token: String) -> Result<Self> {
        Ok(Self { data: token })
    }

    /// Get the attestation result JWT as a string reference
    pub fn as_str(&self) -> &str {
        &self.data
    }

    /// Get the attestation result JWT as a owned string
    pub fn into_str(self) -> String {
        self.data
    }

    pub fn exp(&self) -> Result<u64> {
        let split_token: Vec<&str> = self.data.split('.').collect();
        if split_token.len() != 3 {
            return Err(Error::MissingTokenField {
                detail: "Illegal JWT format".to_string(),
            });
        }

        let claims = URL_SAFE_NO_PAD
            .decode(split_token[1])
            .map_err(Error::Base64DecodeFailed)?;
        let claims_value =
            serde_json::from_slice::<Value>(&claims).map_err(Error::ParseJwtClaimsFailed)?;

        let Some(exp) = claims_value["exp"].as_u64() else {
            return Err(Error::MissingTokenField {
                detail: "token expiration unset".to_string(),
            });
        };

        Ok(exp)
    }
}

impl GenericEvidence for CocoAsToken {
    fn get_dice_cbor_tag(&self) -> u64 {
        OCBR_TAG_EVIDENCE_COCO_TOKEN
    }

    fn get_dice_raw_evidence(&self) -> Result<Vec<u8>> {
        Ok(self.data.as_bytes().to_owned())
    }

    fn get_claims(&self) -> Result<Claims> {
        let split_token: Vec<&str> = self.data.split('.').collect();
        if split_token.len() != 3 {
            return Err(Error::MissingTokenField {
                detail: "Illegal JWT format".to_string(),
            });
        }
        let claims = URL_SAFE_NO_PAD
            .decode(split_token[1])
            .map_err(Error::Base64DecodeFailed)?;
        let claims_value = {
            let mut claims_value =
                serde_json::from_slice::<serde_json::Map<String, Value>>(&claims)
                    .map_err(Error::ParseJwtClaimsFailed)?;

            if let Some(Value::String(json_str)) = claims_value.get("tcb-status") {
                let tcb_status_claims = serde_json::from_str::<Value>(json_str);
                match tcb_status_claims {
                    Ok(tcb_status_claims) => {
                        claims_value.insert("tcb-status".to_string(), tcb_status_claims);
                    }
                    Err(error) => {
                        tracing::warn!(?error, "failed to parse tcb-status field")
                    }
                }
            }
            Value::Object(claims_value)
        };

        let flattened_claims_value =
            Flattener::new()
                .flatten(&claims_value)
                .map_err(|e| Error::JwtClaimsFlattenFailed {
                    message: e.to_string(),
                })?;

        Ok(match flattened_claims_value {
            Value::Object(m) => m,
            _ => {
                return Err(Error::MissingTokenField {
                    detail: format!("Invalid claims value: {claims_value}"),
                })
            }
        })
    }

    fn create_evidence_from_dice(
        cbor_tag: u64,
        raw_evidence: &[u8],
    ) -> DiceParseEvidenceOutput<Self> {
        if cbor_tag == OCBR_TAG_EVIDENCE_COCO_TOKEN {
            return match std::str::from_utf8(raw_evidence)
                .map_err(Error::InvalidUtf8Slice)
                .map(|token| Self::new(token.to_owned()))
            {
                Ok(Ok(v)) => DiceParseEvidenceOutput::Ok(v),
                Ok(Err(e)) => DiceParseEvidenceOutput::MatchButInvalid(e),
                Err(e) => DiceParseEvidenceOutput::MatchButInvalid(e),
            };
        }
        DiceParseEvidenceOutput::NotMatch
    }
}

#[derive(Serialize, Deserialize)]
struct CocoEvidenceCborHelper {
    pub(self) tee_type: Tee,
    pub(self) aa_evidence: ByteBuf,
    pub(self) aa_additional_evidence: Option<ByteBuf>,
    pub(self) aa_runtime_data: String,
    pub(self) aa_runtime_data_hash_algo: HashAlgoIanaId,
}

impl CocoEvidence {
    #[allow(clippy::wrong_self_convention)]
    fn into_cbor_helper(&self) -> CocoEvidenceCborHelper {
        CocoEvidenceCborHelper {
            tee_type: self.aa_tee_type,
            aa_evidence: ByteBuf::from(self.aa_evidence.to_owned()),
            aa_additional_evidence: self
                .aa_additional_evidence
                .as_ref()
                .map(|e| ByteBuf::from(e.to_owned())),
            aa_runtime_data: self.aa_runtime_data.to_owned(),
            aa_runtime_data_hash_algo: self.aa_runtime_data_hash_algo.into(),
        }
    }

    fn from_cbor_helper(helper: CocoEvidenceCborHelper) -> Result<Self> {
        Ok(Self {
            aa_tee_type: helper.tee_type,
            aa_evidence: helper.aa_evidence.into_vec(),
            aa_additional_evidence: helper.aa_additional_evidence.map(|e| e.into_vec()),
            aa_runtime_data: helper.aa_runtime_data,
            aa_runtime_data_hash_algo: helper.aa_runtime_data_hash_algo.try_into()?,
        })
    }
}

#[derive(Serialize, Deserialize)]
struct CocoEvidenceJsonHelper {
    pub(self) aa_tee_type: Tee,
    // Base64 encoded
    pub(self) aa_evidence: String,
    // Base64 encoded
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(self) aa_additional_evidence: Option<String>,
    pub(self) aa_runtime_data: String,
    pub(self) aa_runtime_data_hash_algo: AttestationServiceHashAlgo,
}

impl CocoEvidence {
    #[allow(clippy::wrong_self_convention)]
    fn into_json_helper(&self) -> CocoEvidenceJsonHelper {
        CocoEvidenceJsonHelper {
            aa_tee_type: self.aa_tee_type,
            aa_evidence: BASE64_STANDARD.encode(&self.aa_evidence),
            aa_additional_evidence: self
                .aa_additional_evidence
                .as_ref()
                .map(|e| BASE64_STANDARD.encode(e)),
            aa_runtime_data: self.aa_runtime_data.clone(),
            aa_runtime_data_hash_algo: self.aa_runtime_data_hash_algo.into(),
        }
    }

    fn from_json_helper(helper: CocoEvidenceJsonHelper) -> Result<Self> {
        Ok(Self {
            aa_tee_type: helper.aa_tee_type,
            aa_evidence: BASE64_STANDARD
                .decode(helper.aa_evidence)
                .map_err(Error::Base64DecodeFailed)?,
            aa_additional_evidence: match helper.aa_additional_evidence {
                Some(e) => Some(
                    BASE64_STANDARD
                        .decode(e)
                        .map_err(Error::Base64DecodeFailed)?,
                ),
                None => None,
            },
            aa_runtime_data: helper.aa_runtime_data,
            aa_runtime_data_hash_algo: helper.aa_runtime_data_hash_algo.into(),
        })
    }
}
