use serde::{Deserialize, Serialize};

use crate::tunnel::provider::ProviderType;

pub mod header;
pub mod metadata;
pub mod userdata;

/// Request structure for the key configuration endpoint
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct KeyConfigRequest {
    /// The request for attestation of server side
    pub attestation_request: Option<AttestationRequest>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "snake_case", tag = "model")]
pub enum AttestationRequest {
    Passport,

    BackgroundCheck {
        /// Challenge token. This is a JWT string obtained from the attestation service
        challenge_token: String,
    },
}

/// Response structure for the key configuration endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct KeyConfigResponse {
    /// HPKE (Hybrid Public Key Encryption) key configuration
    pub hpke_key_config: HpkeKeyConfig,

    /// Attestation information - can be either an attestation result (passport model)
    /// or evidence (background check model)
    pub attestation_info: Option<ServerAttestationInfo>,
}

/// HPKE key configuration structure
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct HpkeKeyConfig {
    /// Expiration timestamp for this configuration
    pub expire_timestamp: u64,

    /// A base64 encoded list of key configurations, each entry is a Individual key configuration entry. Defined in Section 3.1 of RFC 9458.
    pub encoded_key_config_list: String,
}

/// Enum to differentiate between passport model and background check model
/// for attestation information in the key configuration response
#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "snake_case", tag = "model")]
pub enum ServerAttestationInfo {
    /// Passport model - server provides attestation result
    Passport {
        /// A JWT string representing the server's own Attestation Result
        /// This is used only in Client verification + passport model scenario
        attestation_result: String,
        /// Which AS/token provider produced `attestation_result`. Omitted on the wire for legacy clients.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        as_provider: Option<ProviderType>,
    },

    /// Background check model - server provides evidence
    BackgroundCheck {
        /// Evidence data containing the nonce
        /// This is used only in Client verification + background check model scenario
        evidence: serde_json::Value,
        /// Which provider the `evidence` JSON belongs to. Omitted for legacy clients.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        aa_provider: Option<ProviderType>,
    },
}

/// Response structure for the attestation challenge endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationChallengeResponse {
    /// A JWT string containing the challenge token
    pub challenge_token: String,
}

/// Request structure for the attestation verification endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationVerifyRequest {
    /// Evidence data containing the nonce
    pub evidence: serde_json::Value,
    /// Which provider the `evidence` JSON belongs to. Omitted for legacy clients.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub aa_provider: Option<ProviderType>,
}

/// Response structure for the attestation verification endpoint
#[derive(Serialize, Deserialize, Debug)]
pub struct AttestationVerifyResponse {
    /// The attestation result JWT generated by the Attestation Service
    pub attestation_result: String,
    /// Which AS/token provider produced `attestation_result`. Omitted for legacy clients.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub as_provider: Option<ProviderType>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn legacy_passport_info_deserializes_without_provider() {
        let json = json!({
            "model": "passport",
            "attestation_result": "eyJ0eXAiOiJKV1QifQ.e30.dummysig"
        });
        let info: ServerAttestationInfo = serde_json::from_value(json).unwrap();
        match info {
            ServerAttestationInfo::Passport { as_provider, .. } => assert!(as_provider.is_none()),
            _ => panic!("expected Passport"),
        }
    }

    #[test]
    fn legacy_background_check_info_deserializes_without_provider() {
        let json = json!({
            "model": "background_check",
            "evidence": {}
        });
        let info: ServerAttestationInfo = serde_json::from_value(json).unwrap();
        match info {
            ServerAttestationInfo::BackgroundCheck { aa_provider, .. } => {
                assert!(aa_provider.is_none())
            }
            _ => panic!("expected BackgroundCheck"),
        }
    }

    #[test]
    fn provider_fields_present_when_set_and_absent_when_none() {
        let with = ServerAttestationInfo::Passport {
            attestation_result: "jwt".into(),
            as_provider: Some(ProviderType::Coco),
        };
        let without = ServerAttestationInfo::Passport {
            attestation_result: "jwt".into(),
            as_provider: None,
        };
        let json_with = serde_json::to_value(&with).unwrap();
        let json_without = serde_json::to_value(&without).unwrap();

        assert_eq!(json_with["as_provider"], "coco");
        assert!(json_without.get("as_provider").is_none());
    }

    #[test]
    fn verify_request_legacy_round_trip() {
        let legacy = json!({"evidence": {}});
        let req: AttestationVerifyRequest = serde_json::from_value(legacy.clone()).unwrap();
        assert!(req.aa_provider.is_none());
        assert_eq!(serde_json::to_value(&req).unwrap(), legacy);
    }

    #[test]
    fn verify_request_with_provider_round_trip() {
        let wire = json!({"evidence": {}, "aa_provider": "coco"});
        let req: AttestationVerifyRequest = serde_json::from_value(wire.clone()).unwrap();
        assert_eq!(req.aa_provider.unwrap(), ProviderType::Coco);
        assert_eq!(serde_json::to_value(&req).unwrap(), wire);
    }

    #[test]
    fn verify_response_legacy_round_trip() {
        let legacy = json!({"attestation_result": "jwt"});
        let resp: AttestationVerifyResponse = serde_json::from_value(legacy.clone()).unwrap();
        assert!(resp.as_provider.is_none());
        assert_eq!(serde_json::to_value(&resp).unwrap(), legacy);
    }

    #[test]
    fn verify_response_with_provider_round_trip() {
        let wire = json!({"attestation_result": "jwt", "as_provider": "coco"});
        let resp: AttestationVerifyResponse = serde_json::from_value(wire.clone()).unwrap();
        assert_eq!(resp.as_provider.unwrap(), ProviderType::Coco);
        assert_eq!(serde_json::to_value(&resp).unwrap(), wire);
    }
}
