use std::any::Any;

use as_any::{AsAny, Downcast};

use super::{
    claims::Claims, DiceParseEvidenceOutput, GenericAttester, GenericEvidence, GenericVerifier,
    TeeType,
};
use crate::{errors::*, tee::ReportData};

pub trait LocalEvidence: AsAny + GenericEvidence {
    /// Return the type of Trusted Execution Environment (TEE) associated with the evidence.
    fn get_tee_type(&self) -> TeeType;
}

impl LocalEvidence for AutoEvidence {
    fn get_tee_type(&self) -> TeeType {
        self.0.get_tee_type()
    }
}

/// A evidence wrapper struct representing evidence generated by `AutoAttester`.
pub struct AutoEvidence(Box<dyn LocalEvidence + Sync>);

impl GenericEvidence for AutoEvidence {
    fn get_dice_cbor_tag(&self) -> u64 {
        self.0.get_dice_cbor_tag()
    }

    fn get_dice_raw_evidence(&self) -> Result<Vec<u8>> {
        self.0.get_dice_raw_evidence()
    }

    fn create_evidence_from_dice(
        #[allow(unused)] _cbor_tag: u64,
        #[allow(unused)] _raw_evidence: &[u8],
    ) -> DiceParseEvidenceOutput<Self> {
        // Only CoCo TEE types are supported, AutoEvidence does not handle evidence parsing directly
        DiceParseEvidenceOutput::NotMatch
    }

    fn get_claims(&self) -> Result<Claims> {
        self.0.get_claims()
    }
}

/// A attester wrapper for automatically selecting and managing different attester implementations based on the detected TEE environment.
pub struct AutoAttester {}

impl AutoAttester {
    pub fn new() -> Self {
        Self {}
    }
}

impl Default for AutoAttester {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait::async_trait]
impl GenericAttester for AutoAttester {
    type Evidence = AutoEvidence;

    async fn get_evidence(
        &self,
        #[allow(unused)] _report_data: &ReportData,
    ) -> Result<Self::Evidence> {
        // Only CoCo TEE types are supported, AutoAttester does not provide attestation directly
        Err(Error::kind_with_msg(
            ErrorKind::UnsupportedTeeType,
            "No TEE was detected on this environment, or the corresponding features (like `attester-*`) may be missing.",
        ))
    }
}

pub struct AutoVerifier {}

impl AutoVerifier {
    pub fn new() -> Self {
        Self {}
    }
}

impl Default for AutoVerifier {
    fn default() -> Self {
        Self::new()
    }
}

/// A verifier wrapper for verifying `AutoEvidence` by automatically selecting different verifier implementations based on the underlying evidence type of `AutoEvidence`.
#[async_trait::async_trait]
impl GenericVerifier for AutoVerifier {
    type Evidence = AutoEvidence;

    async fn verify_evidence(
        &self,
        evidence: &Self::Evidence,
        #[allow(unused)] _report_data: &ReportData,
    ) -> Result<()> {
        let tee_type = evidence.0.get_tee_type();
        // Only CoCo TEE types are supported
        Err(Error::kind_with_msg(
            ErrorKind::UnsupportedTeeType,
            format!("no verifier for tee type {tee_type:?}, the corresponding features (like `verifier-*`) may be missing.")
        ))
    }
}

#[cfg(test)]
pub mod tests {

    use crate::errors::*;

    use super::*;

    #[tokio::test]
    async fn test_auto_attester_and_auto_verifier_on_non_tee() -> Result<()> {
        // With only CoCo support, AutoAttester always returns UnsupportedTeeType
        let report_data = ReportData::Raw(b"test_report_data".to_vec());
        let attester = AutoAttester::new();
        let res = attester.get_evidence(&report_data).await;
        assert!(res.is_err());
        let Err(err) = res else { panic!() };
        assert_eq!(err.get_kind(), ErrorKind::UnsupportedTeeType);
        Ok(())
    }
}
