name: Test Build Docker Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Build Docker Image
      run: |
        DOCKER_BUILDKIT=1 docker build -t tng:latest --target tng-release -f Dockerfile .
