name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest-16-cores
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 
          - ghcr.io/inclavare-containers/tng:latest
          - ghcr.io/inclavare-containers/tng:${{ github.sha }}
        target: tng-release
        context: .
